import type { Metadata } from "next";
import "./globals.css";
import Nav from "@/components/nav/page";

export const metadata: Metadata = {
  title: "Grievance Portal Trial",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
